#Variabel dan tipe data

L = 4 #integer
S = 2
M = "Makan" #string
a = "45"
#float Angka desimal
b = 3.25
e = 2
#Bolean True or Fault

#Aritmatika
X = L - S
print("Hasil pengurangannya adalah", X)
F = L + S
print("Maka hasil penjmlahan adalah", F)
Y = b * e
print("maka hasil perkaliannya adalah", Y)
Z = L ** S
print("maka hasil pangkatnya adalah", Z)
O = L / S
print("maka hasil pembagiannya adalah", O)
K = b // e
print("Hasil pembagiannya adalah", K)
T = L % S 
print("modulusnya adalah", T)

persegi_panjang = int(input ("Masukkan panjang "))
persegi_panjang2 = int(input ("Masukkan lebar "))
hitung = persegi_panjang * persegi_panjang2
print("maka lebarnya adalah", hitung)